# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_text', models.CharField(max_length=400)),
                ('cookies', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIDs_text', models.CharField(max_length=400)),
                ('users', models.EmailField(max_length=50)),
                ('user_cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzy_app.Cookie')),
            ],
        ),
    ]
